# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

junit:
  # Docker image with Java, JavaFX and Maven, home made for us:
  image: forge.univ-lyon1.fr:4567/forge_public/ci-images/maven-ucbl:3-jdk-11
  # alternative: use image: maven and 'apt install openjfx' in
  # before_script.
  script:
    - echo "Continuous integration not set up"; exit 1
